repos:
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.16
    hooks:
      - id: helmlint
  - repo: git://github.com/pre-commit/pre-commit-hooks
    sha: 46251c9523506b68419aefdf5ff6ff2fbc4506a4
    hooks:
      - id: check-added-large-files
      - id: detect-private-key
      - id: trailing-whitespace
