apiVersion: v2
appVersion: 0.5.0
description: A Helm chart for deploying the Zimagi.
home: https://github.com/zimagi/zimagi
icon: https://github.com/zimagi/zimagi/blob/master/docs/_static/logo.png
name: zimagi
type: application
version: 1.0.11
