apiVersion: v2
version: 2.0.0
appVersion: 0.11.14

name: zimagi
type: application
description: A Helm chart for deploying the Zimagi data management platform.
home: https://github.com/zimagi/zimagi
icon: https://github.com/zimagi/zimagi/blob/master/docs/_static/logo.png

dependencies:
- condition: postgresql.enabled
  name: postgresql
  repository: https://charts.bitnami.com/bitnami
  version: 12.1.1
- condition: redis.enabled
  name: redis
  repository: https://charts.bitnami.com/bitnami
  version: 17.3.11
- name: zimagi-lib
  repository: https://charts.zimagi.com
  version: 0.0.4

maintainers:
- email: erik.jagyugya@dccs.tech
  name: jagyugyaerik
  url: https://github.com/jagyugyaerik
- email: adrian.webb@dccs.tech
  name: adrianwebb
  url: https://github.com/adrianwebb
