apiVersion: v2
name: zimagi
version: 1.0.4
description: A Helm chart for deploying the Zimagi.
type: application
home: https://github.com/zimagi/zimagi
icon: https://github.com/zimagi/zimagi/blob/master/docs/_static/logo.png
appVersion: "0.5.0"
