apiVersion: v2
appVersion: 0.8.10
dependencies:
- condition: postgresql.enabled
  name: postgresql
  repository: https://charts.bitnami.com/bitnami
  version: 10.9.1
- condition: redis.enabled
  name: redis
  repository: https://charts.bitnami.com/bitnami
  version: 14.8.7
- name: common
  repository: https://charts.bitnami.com/bitnami
  tags:
  - bitnami-common
  version: 1.8.0
description: A Helm chart for deploying the Zimagi data management platform.
home: https://github.com/zimagi/zimagi
icon: https://github.com/zimagi/zimagi/blob/master/docs/_static/logo.png
maintainers:
- email: jagyugyaerik@gmail.com
  name: jagyugyaerik
  url: https://github.com/jagyugyaerik
- email: adrian.webb@dccs.tech
  name: adrianwebb
  url: https://github.com/adrianwebb
name: zimagi
type: application
version: 1.0.38
