apiVersion: v2
version: 2.7.14
appVersion: 0.14.17

name: zimagi
type: application
description: A Helm chart for deploying the Zimagi data management platform.
home: https://github.com/zimagi/zimagi
icon: https://raw.githubusercontent.com/zimagi/zimagi/main/docs/_static/logo.png

dependencies:
  - condition: postgresql.enabled
    name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 16.7.x
  - condition: redis.enabled
    name: redis
    repository: https://charts.bitnami.com/bitnami
    version: 21.2.x
  - condition: qdrant.enabled
    name: qdrant
    repository: https://qdrant.github.io/qdrant-helm
    version: 1.15.x
  - name: reactor
    repository: https://charts.kube-reactor.com
    version: 0.2.x

maintainers:
  - email: adrian@fractalsynapse.com
    name: adrianwebb
    url: https://github.com/adrianwebb
