apiVersion: v2
version: 2.5.49
appVersion: 0.14.3

name: zimagi
type: application
description: A Helm chart for deploying the Zimagi data management platform.
home: https://github.com/zimagi/zimagi
icon: https://raw.githubusercontent.com/zimagi/zimagi/main/docs/_static/logo.png

dependencies:
  - condition: postgresql.enabled
    name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 15.4.x
  - condition: redis.enabled
    name: redis
    repository: https://charts.bitnami.com/bitnami
    version: 19.5.x
  - name: zimagi-lib
    repository: https://charts.zimagi.com
    version: 0.x.x

maintainers:
  - email: adrian@fractalsynapse.com
    name: adrianwebb
    url: https://github.com/adrianwebb
