apiVersion: v2
version: 2.5.33
appVersion: 0.13.32

name: zimagi
type: application
description: A Helm chart for deploying the Zimagi data management platform.
home: https://github.com/zimagi/zimagi
icon: https://raw.githubusercontent.com/zimagi/zimagi/main/docs/_static/logo.png

dependencies:
- condition: postgresql.enabled
  name: postgresql
  repository: https://charts.bitnami.com/bitnami
  version: 15.x.x
- condition: redis.enabled
  name: redis
  repository: https://charts.bitnami.com/bitnami
  version: 19.x.x
- name: zimagi-lib
  repository: https://charts.zimagi.com
  version: 0.x.x

maintainers:
- email: erik@fractalsynapse.com
  name: jagyugyaerik
  url: https://github.com/jagyugyaerik
- email: adrian@fractalsynapse.com
  name: adrianwebb
  url: https://github.com/adrianwebb
