apiVersion: v2
appVersion: 0.11.13
dependencies:
- condition: postgresql.enabled
  name: postgresql
  repository: https://charts.bitnami.com/bitnami
  version: 12.1.1
- condition: redis.enabled
  name: redis
  repository: https://charts.bitnami.com/bitnami
  version: 17.3.11
- name: common
  repository: https://charts.bitnami.com/bitnami
  tags:
  - bitnami-common
  version: 1.16.1
description: A Helm chart for deploying the Zimagi data management platform.
home: https://github.com/zimagi/zimagi
icon: https://github.com/zimagi/zimagi/blob/master/docs/_static/logo.png
maintainers:
- email: erik.jagyugya@dccs.tech
  name: jagyugyaerik
  url: https://github.com/jagyugyaerik
- email: adrian.webb@dccs.tech
  name: adrianwebb
  url: https://github.com/adrianwebb
name: zimagi
type: application
version: 1.0.72
