global:
  data:
    ZIMAGI_APP_NAME: zimagi
    ZIMAGI_DEFAULT_RUNTIME_REPO: "${container_registry}"
    ZIMAGI_DEFAULT_RUNTIME_IMAGE: "zimagi:${zimagi_version}"
    ZIMAGI_REDIS_TYPE: redis
    ZIMAGI_ENCRYPT_DATA: true
    ZIMAGI_DB_MAX_CONNECTIONS: 100
    ZIMAGI_THREAD_COUNT: 5
    ZIMAGI_MUTEX_TTL_SECONDS: 432000
    ZIMAGI_DEBUG: false
    ZIMAGI_LOG_LEVEL: warning
    ZIMAGI_EMAIL_HOST: ${smtp_server_domain}
    ZIMAGI_EMAIL_PORT: ${smtp_server_port}
    ZIMAGI_EMAIL_USE_TLS: true
    ZIMAGI_EMAIL_SUBJECT_PREFIX: "[Zimagi]> "

command-api:
  data:
    ZIMAGI_SERVER_WORKERS: 1
    ZIMAGI_DISABLE_HTTPS: true
    ZIMAGI_ENCRYPT_COMMAND_API: false

data-api:
  data:
    ZIMAGI_SERVER_WORKERS: 1
    ZIMAGI_DISABLE_HTTPS: true
    ZIMAGI_ENCRYPT_DATA_API: false
    ZIMAGI_DISABLE_PAGE_CACHE: false
    ZIMAGI_PAGE_CACHE_SECONDS: 86400
    ZIMAGI_REST_PAGE_COUNT: 50

scheduler:
  data: {}

worker:
  data:
    ZIMAGI_WORKER_MAX_PROCESSES: 1

flower:
  data: {}
