zimagi-db:
  data:
    postgres-password: "${postgresql.password}"
    replication-password: "${postgresql.password}"
    password: "${postgresql.password}"
    redis-password: "${redis.password}"

origin-cert:
  data:
    "server.key": "${certificate_key}"
    "server.crt": "${certificate_cert}"

global:
  data:
    ZIMAGI_POSTGRES_PASSWORD: "${postgresql.password}"
    ZIMAGI_REDIS_PASSWORD: "${redis.password}"
    ZIMAGI_USER_PASSWORD: "${zimagi_os_password}"
    ZIMAGI_SECRET_KEY: "${zimagi_secret_key}"
    ZIMAGI_ADMIN_API_KEY: "${zimagi_admin_api_key}"
    ZIMAGI_EMAIL_HOST_USER: "${zimagi_email_host_user}"
    ZIMAGI_EMAIL_HOST_PASSWORD: "${zimagi_email_host_password}"
