version: 2.1
orbs:
  shellcheck: circleci/shellcheck@2.0.0
jobs:
  lint-charts:
    docker:
      - image: quay.io/helmpack/chart-testing:v3.4.0
    steps:
      - checkout
      - run:
          name: lint
          command: |
            git remote add upstream https://github.com/paulczar/percona-helm-charts
            git fetch upstream master
            ct lint --config .circleci/ct.yaml
  install-charts:
    machine: true
    steps:
      - checkout
      - run:
          no_output_timeout: 12m
          command: .circleci/install_charts.sh
  release-charts:
    machine: true
    steps:
      - checkout
      - run:
          name: Release charts
          command: |
            echo "export GIT_REPOSITORY_URL=$CIRCLE_REPOSITORY_URL" >> $BASH_ENV
            echo "export GIT_USERNAME=$CIRCLE_PROJECT_USERNAME" >> $BASH_ENV
            echo "export GIT_REPOSITORY_NAME=$CIRCLE_PROJECT_REPONAME" >> $BASH_ENV
            .circleci/setup_tools.sh
            .circleci/release.sh
workflows:
  version: 2
  lint-and-install:
    jobs:
      - lint-charts:
          filters:
            branches:
              ignore: master
            tags:
              ignore: /.*/
      - install-charts:
          requires:
            - lint-charts
  release:
    jobs:
      - shellcheck/check:
          dir: .circleci
          filters:
            tags:
              ignore: /.*/
            branches:
              only: master
      - release-charts:
          filters:
            tags:
              ignore: /.*/
            branches:
              only: master