labels: {}
annotations: {}

image:
  pullSecrets: []
  pullPolicy: IfNotPresent
  image: ""
  tag: ""
  entrypoint: ""
  args: []

serviceAccounts: {}

roles: {}
access: []

pvc:
  claims: {}
  mounts: {}

volumes:
  config: {}
  secret: {}
  host: {}

deployment:
  replicaCount: 1
  revisionHistoryLimit: 1

  updateStrategy:
    type: RollingUpdate

  podSecurityContext: {}
  containerSecurityContext: {}

  priorityClassName: ""
  affinity: {}
  podAffinityPreset: ""
  podAntiAffinityPreset: soft
  nodeAffinityPreset:
    type: ""
    key: ""
    values: []

  nodeSelector: {}
  tolerations: []
  resources:
    limits: {}
    requests: {}

  env: {}
  config: []
  secrets: []

  protocol: HTTP
  port: 80

  livenessProbe:
    endpoint: "/"
    failureThreshold: 1
    initialDelaySeconds: 60
    periodSeconds: 5
    successThreshold: 1
    timeoutSeconds: 3

  readinessProbe:
    endpoint: "/"
    failureThreshold: 1
    initialDelaySeconds: 90
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 3

autoscaling:
  minReplicas: 1
  maxReplicas: 4
  avgCpuUtilization: 70

service:
  type: ClusterIP
  protocol: http
  port: 80

ingress:
  className: ''
  hosts: []
  tls: []

services:
  rule-service:
    serviceMonitor:
      enabled: false
      namespace: ""
      jobLabel: ""
      interval: ""
      scrapeTimeout: ""
      selector: {}
      labels: {}
      relabelings: []
      metricRelabelings: []
      honorLabels: false
    prometheusRule:
      rules: []
      # - alert: LowInstance
      #   expr: up{service="{{ template "common.names.fullname" . }}"} < 1
      #   for: 1m
      #   labels:
      #     severity: critical
      #   annotations:
      #     description: Service {{ template "common.names.fullname" . }} Tomcat is down since 1m.
      #     summary: Tomcat instance is down.