apiVersion: v2
version: 0.1.22

name: argocd-apps
type: application
description: Deploy ArgoCD Applications from a collection of Helm Charts

dependencies:
- name: common
  repository: https://charts.bitnami.com/bitnami
  version: 2.2.2
  tags:
  - bitnami-common

maintainers:
- email: erik.jagyugya@dccs.tech
  name: jagyugyaerik
  url: https://github.com/jagyugyaerik
- email: adrian.webb@dccs.tech
  name: adrianwebb
  url: https://github.com/adrianwebb
