{{- range $key,$app := .Values.applications }}
{{- if $app.enabled }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $app.metadata.applicationName }}
  namespace: {{ coalesce $.Values.common.applications.metadata.argocdNamespace "argocd" }}
  {{- if $app.metadata.annotations }}
  annotations:
  {{ toYaml $app.metadata.annotations | nindent 4  }}
  {{- end }}
spec:
  project: default

  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=false
    {{- if $app.syncOptions.replace }}
    - Replace=true
    {{- end }}

  source:
    path: {{ $app.source.path | default nil }}
    chart: {{ $app.source.chart | default nil }}
    repoURL: {{ $app.source.repoURL }}
    targetRevision: {{ $app.source.targetRevision }}

    helm:
      skipCrds: {{ $app.source.helm.skipCrds }}
      releaseName: {{ $app.source.helm.releaseName }}
      {{- if $app.source.helm.values }}
      values: {{ toYaml $app.source.helm.values | nindent 8 }}
      {{- end }}

{{- if $app.source.extraSourceFields }}
{{ tpl $app.source.extraSourceFields $ | indent 4 }}
{{- else if and $.Values.common.applications.source $.Values.common.applications.source.extraSourceFields }}
{{ tpl $.Values.common.applications.source.extraSourceFields $ | indent 4 }}
{{- end }}

  destination:
    server: "https://kubernetes.default.svc"
    namespace: {{ coalesce $app.destination.namespace $.Values.common.applications.metadata.namespace }}

{{- if $app.extraFields }}
{{ tpl $app.extraFields $ | indent 2 }}
{{- else if $.Values.common.applications.extraFields }}
{{ tpl $.Values.common.applications.extraFields $ | indent 2 }}
{{- end }}
{{- end }}
{{- end }}
