{{- range $key,$app := .Values.applications }}
{{- if and $app.enabled $app.config }}
{{- range $name,$config := $app.config }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $name }}
  namespace: {{ $app.metadata.name }}
data:
  {{- range $env_var,$env_value := $config }}
  {{ $env_var }}: {{ $env_value | toString | quote }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
