{{- range $key,$app := .Values.applications }}
{{- if and $app.enabled $app.config }}
{{- range $name,$config := $app.config }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $name }}
  namespace: {{ coalesce $app.destination.namespace $.Values.common.applications.metadata.namespace }}
data:
  {{- range $env_var,$env_value := $config }}
  {{ $env_var }}: {{ include "common.tplvalues.render" (dict "value" $env_value "context" $) | quote }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
