{{- range $key,$app := .Values.applications }}
{{- $namespace := coalesce $app.destination.namespace $.Values.common.applications.metadata.namespace }}
{{- if and $app.enabled $namespace }}
{{- if not (lookup "v1" "Namespace" "" $namespace) }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $namespace }}
{{- end }}
{{- end }}
{{- end }}
