{{- range $key,$app := .Values.applications }}
{{- if and $app.enabled $app.secrets }}
{{- range $name,$secrets := $app.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  namespace: {{ coalesce $app.destination.namespace $.Values.common.applications.metadata.namespace }}
type: Opaque
data:
  {{- range $env_var,$env_value := $secrets }}
  {{ $env_var }}: {{ include "common.tplvalues.render" (dict "value" $env_value "context" $) | quote }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
