{{- range $key,$values := .Values.applications }}
{{- if and $values.enabled $values.destination.registryCredential }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $values.metadata.applicationName }}
  namespace: {{ $values.destination.namespace }}
type: kubernetes.io/dockerconfigjson
data:
  ".dockerconfigjson": {{ $values.destination.registryCredential }}
{{- end }}
{{- end }}
