{{- range $key,$app := .Values.applications }}
{{- if and $app.enabled $app.secrets }}
{{- range $name,$secrets := $app.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  namespace: {{ $app.metadata.name }}
type: Opaque
data:
  {{- range $env_var,$env_value := $secrets }}
  {{ $env_var }}: {{ $env_value | b64enc | quote }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
