affinity: {}
autoscaling:
  enabled: false
  maxReplicas: 100
  minReplicas: 1
  targetCPUUtilizationPercentage: 80
fullnameOverride: ''
image:
  pullPolicy: IfNotPresent
  repository: zimagi/zimagi
  tag: test
imagePullSecrets: []
ingress:
  annotations: {}
  enabled: false
  hostName: ''
  http:
    path: ''
    servicePort: 80
nameOverride: ''
nodeSelector: {}
podAnnotations: {}
podSecurityContext: {}
postgres: {}
redis: {}
replicaCount: 1
resources: {}
securityContext: {}
service:
  command:
    name: command
    port: 80
    targetPort: 5123
    type: ClusterIP
  data:
    name: data
    port: 80
    targetPort: 5323
    type: ClusterIP
serviceAccount:
  annotations: {}
  create: true
  name: ''
tolerations: []
