apiVersion: v2
version: 1.1.5
appVersion: 0.0.0

name: application
type: application
description: A Helm chart for deploying flexible applications.
home: https://github.com/zimagi/charts

dependencies:
- name: zimagi-lib
  repository: https://charts.zimagi.com
  version: 0.x.x

maintainers:
- email: erik@fractalsynapse.com
  name: jagyugyaerik
  url: https://github.com/jagyugyaerik
- email: adrian@fractalsynapse.com
  name: adrianwebb
  url: https://github.com/adrianwebb
