nameOverride: ""

labels: {}
annotations: {}

image:
  pullSecrets: []
  pullPolicy: IfNotPresent
  repository: registry.hub.docker.com
  image: "" # Required
  tag: ""   # Required

roles: {}
access: []

pvc:
  claims: {}
  mounts: {}

volumes:
  config: {}
  secret: {}

deployment:
  replicaCount: 1
  updateStrategy:
    type: RollingUpdate

  priorityClassName: ""
  affinity: {}
  podAffinityPreset: ""
  podAntiAffinityPreset: soft
  nodeAffinityPreset:
    type: ""
    key: ""
    values: []

  nodeSelector: {}
  tolerations: []
  resources:
    limits: {}
    requests: {}

  env: {}
  config: []  # Config map names
  secrets: [] # Secret names

  protocol: HTTP
  port: 80

  livenessProbe:
    endpoint: "/"
    failureThreshold: 6
    initialDelaySeconds: 10
    periodSeconds: 5
    successThreshold: 1
    timeoutSeconds: 5

  readinessProbe:
    endpoint: "/"
    failureThreshold: 3
    initialDelaySeconds: 10
    periodSeconds: 5
    successThreshold: 3
    timeoutSeconds: 5

autoscaling:
  minReplicas: 1
  maxReplicas: 4
  avgCpuUtilization: 70

service:
  type: ClusterIP
  protocol: http
  port: 80

ingress:
  className: ''
  hosts: []
  tls: []

services: {} # Service definitions here!!!
