{{/*
Service annotations
*/}}
{{- define "zimagi-lib.annotations" -}}
{{- $root := (index . 0) -}}
{{- $service := (index . 1) -}}
{{- $annotations := merge ($service.annotations | default (dict )) $root.Values.annotations -}}
{{- if $annotations -}}
{{- range $key, $value := $annotations -}}
{{ $key }}: {{ $value | quote }}
{{ end -}}
{{- end -}}
{{- end -}}
