{{/*
Generate a multi-service application
*/}}
{{- define "zimagi-lib.app" -}}
{{- $root := (index . 0) -}}
{{- $app := (index . 1) | default $root -}}
---
{{- range $name, $account := $root.Values.serviceAccounts -}}
{{ template "zimagi-lib.serviceAccount" (list $root $account $name) }}
{{- end -}}
{{- range $name, $role := $root.Values.roles -}}
{{ template "zimagi-lib.role" (list $root $role $name) }}
{{- end -}}
{{- range $name, $account := $root.Values.serviceAccounts -}}
{{ template "zimagi-lib.roleBinding" (list $root $account $name) }}
{{- end -}}
{{- range $name, $claim := $root.Values.pvc.claims -}}
{{ template "zimagi-lib.pvc" (list $root $claim $name) }}
{{- end -}}
{{- range $name, $service := $app.services -}}
{{- $schema := merge $service (dict "name" $name) -}}
{{ template "zimagi-lib.serviceAccount" (list $root $schema "") }}
{{ template "zimagi-lib.roleBinding" (list $root $schema "") }}
{{ template "zimagi-lib.servicePvc" (list $root $schema) }}
{{ template "zimagi-lib.deployment" (list $root $schema) }}
{{ template "zimagi-lib.autoscaler" (list $root $schema) }}
{{ template "zimagi-lib.service" (list $root $schema) }}
{{ template "zimagi-lib.ingress" (list $root $schema) }}
{{- end -}}
{{- end -}}
