{{/*
Create chart name and version as used by the chart label
*/}}
{{- define "zimagi-lib.chart" -}}
{{- include "common.names.chart" . -}}
{{- end -}}

{{/*
Selector labels
*/}}
{{- define "zimagi-lib.selectorLabels" -}}
{{- $root := (index . 0) -}}
{{- $service := (index . 1) -}}
app.kubernetes.io/name: {{ include "zimagi-lib.name" $root }}
app.kubernetes.io/instance: {{ $root.Release.Name }}
app.kubernetes.io/component: {{ include "zimagi-lib.serviceName" (list $root $service) }}
{{- end -}}

{{/*
Service labels
*/}}
{{- define "zimagi-lib.labels" -}}
{{- $root := (index . 0) -}}
{{- $service := (index . 1) -}}
helm.sh/chart: {{ include "zimagi-lib.chart" $root }}
{{- if $root.Chart.AppVersion -}}
app.kubernetes.io/version: {{ $root.Chart.AppVersion | quote }}
{{- end -}}
app.kubernetes.io/managed-by: {{ $root.Release.Service }}
{{ include "zimagi-lib.selectorLabels" (list $root $service) }}
app.kubernetes.io/component: {{ include "zimagi-lib.serviceName" (list $root $service) }}
{{- range $key, $value := merge $service.labels $root.Values.labels -}}
{{ $key }}: {{ $value | quote }}
{{- end -}}
{{- end -}}
