{{/*
Expand the name of the chart
*/}}
{{- define "zimagi-lib.name" -}}
{{- include "common.names.name" . -}}
{{- end -}}

{{/*
Get a service name
*/}}
{{- define "zimagi-lib.serviceName" -}}
{{- $root := (index . 0) -}}
{{- $service := (index . 1) -}}
{{- $name_override := (index . 2) -}}
{{- ternary $service.name $name_override (eq $name_override "") -}}
{{- end -}}

{{/*
Get a volume name from mount data
*/}}
{{- define "zimagi-lib.volumeName" -}}
{{- if kindIs "string" . -}}
{{- . -}}
{{- else -}}
{{- .name -}}
{{- end -}}
{{- end -}}