{{/*
Expand the name of the chart
*/}}
{{- define "zimagi-lib.name" -}}
{{- include "common.names.name" . -}}
{{- end -}}

{{/*
Create a default fully qualified service name
We truncate at 63 chars because some Kubernetes name fields are limited to this (by the DNS naming spec)
*/}}
{{- define "zimagi-lib.serviceName" -}}
{{- $root := (index . 0) -}}
{{- $service := (index . 1) -}}
{{- printf "%s-%s" (include "common.names.fullname" $root) $service.name | trunc 63 | trimSuffix "-" -}}
{{- end -}}
