{{/*
Generate shared persistent volume claims
*/}}
{{- define "zimagi-lib.pvc" -}}
{{- $root := (index . 0) -}}
{{- $claim := (index . 1) -}}
{{- $name := (index . 2) -}}
{{- if $claim }}
---
kind: PersistentVolumeClaim
apiVersion: v1
{{- $name := include "zimagi-lib.serviceName" (list $root nil $name) }}
{{ include "zimagi-lib.metadata" (list $root $claim $name) }}
spec:
  storageClassName: {{ $claim.storageClass | quote }}
  accessModes:
    - {{ $claim.accessMode | quote }}
  resources:
    requests:
      storage: {{ $claim.size | quote }}
{{- end -}}
{{- end -}}

{{/*
Generate individual service persistent volume claims
*/}}
{{- define "zimagi-lib.servicePvc" -}}
{{- $root := (index . 0) -}}
{{- $service := (index . 1) -}}
{{- $pvc := ($service.pvc | default (dict )) -}}
{{- range $name, $claim := ($pvc.claims | default (dict )) -}}
{{ template "zimagi-lib.pvc" (list $root $claim $name) }}
{{- end -}}
{{- end -}}
