{{/*
Generate persistent volume claims
*/}}
{{- define "zimagi-lib.pvc" -}}
{{- $root := (index . 0) -}}
{{- $service := (index . 1) -}}
{{- range $name, $claim := merge $service.pvc.claims $root.Values.pvc.claims -}}
{{- if $claim -}}
---
kind: PersistentVolumeClaim
apiVersion: v1
{{ include "zimagi-lib.metadata" (list $root $service $name) }}
spec:
  storageClassName: {{ $claim.storageClass | quote }}
  accessModes:
    - {{ $claim.accessMode | quote }}
  resources:
    requests:
      storage: {{ $claim.size | quote }}
{{- end -}}
{{- end -}}
{{- end -}}

{{- define "zimagi-lib.pvc.ext" -}}
{{- include "zimagi-lib.util.merge" (append . "zimagi-lib.pvc") -}}
{{- end -}}
