{{/*
Generate service role bindings
*/}}
{{- define "zimagi-lib.roleBinding" -}}
{{- $root := (index . 0) -}}
{{- $service := (index . 1) -}}
{{- $name := (index . 2) -}}
{{- range $role_name := ((ternary (coalesce $service.access $root.Values.access) $service.access (eq $name "")) | default (list )) -}}
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
{{- $name := ternary (include "zimagi-lib.serviceName" (list $root $service)) $name (eq $name "") }}
{{ include "zimagi-lib.metadata" (list $root $service $name) }}
subjects:
  - kind: ServiceAccount
    namespace: {{ $root.Release.Namespace | quote }}
    name: {{ $name | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: {{ if (get ((get $root.Values.roles $role_name) | default (dict )) "global") -}}ClusterRole{{- else -}}Role{{- end }}
  name: {{ $role_name | quote }}
{{ end -}}
{{- end -}}
