{{/*
Generate cluster or namespace role binding
*/}}
{{- define "zimagi-lib.role" -}}
{{- $root := (index . 0) -}}
{{- $role := (index . 1) -}}
{{- $name := (index . 2) -}}
{{- if $role }}
---
kind: {{ if (index $role "global") -}}ClusterRole{{- else -}}Role{{- end }}
apiVersion: rbac.authorization.k8s.io/v1
{{ include "zimagi-lib.metadata" (list $root nil $name) }}
rules:
{{- range $policy := $role.rules }}
  - apiGroups: {{ include "zimagi-lib.util.ensureList" $policy.apiGroups | nindent 6 }}
    nonResourceURLs: {{ include "zimagi-lib.util.ensureList" $policy.nonResourceURLs | nindent 6 }}
    resourceNames: {{ include "zimagi-lib.util.ensureList" $policy.resourceNames | nindent 6 }}
    resources: {{ include "zimagi-lib.util.ensureList" $policy.resources | nindent 6 }}
    verbs: {{ include "zimagi-lib.util.ensureList" $policy.verbs | nindent 6 }}
{{- end -}}
{{- end -}}
{{- end -}}
