{{/*
Generate a service account
*/}}
{{- define "zimagi-lib.serviceAccount" -}}
{{- $root := (index . 0) -}}
{{- $service := (index . 1) -}}
{{- $name := (index . 2) }}
---
apiVersion: v1
kind: ServiceAccount
{{- $name := include "zimagi-lib.serviceName" (list $root $service $name) }}
{{ include "zimagi-lib.metadata" (list $root $service $name) }}
{{- end -}}
