{{/*
Generate a service account
*/}}
{{- define "zimagi-lib.serviceAccount" -}}
{{- $root := (index . 0) -}}
{{- $service := (index . 1) }}
---
apiVersion: v1
kind: ServiceAccount
{{- $name := include "zimagi-lib.serviceName" (list $root $service) }}
{{ include "zimagi-lib.metadata" (list $root $service $name) }}
{{- end -}}

{{- define "zimagi-lib.serviceAccount.ext" -}}
{{- include "zimagi-lib.util.merge" (append . "zimagi-lib.serviceAccount") -}}
{{- end -}}
