{{/*
Generate a service
*/}}
{{- define "zimagi-lib.service" -}}
{{- $root := (index . 0) -}}
{{- $service := (index . 1) -}}
{{- $app_deployment := ($service.deployment | default (dict )) -}}
{{- $app_service := ($service.service | default (dict )) -}}
{{- if $app_service.enabled }}
---
apiVersion: v1
kind: Service
{{- $name := include "zimagi-lib.serviceName" (list $root $service "") }}
{{ include "zimagi-lib.metadata" (list $root $service $name) }}
spec:
  {{- $container_port := coalesce $app_deployment.port $root.Values.deployment.port -}}
  {{- $service_type := coalesce $app_service.type $root.Values.service.type -}}
  {{- $service_port := coalesce $app_service.port $root.Values.service.port -}}
  {{- $node_port := coalesce $app_service.nodePort $root.Values.service.nodePort }}
  type: {{ $service_type }}
  ports:
    - name: {{ $name | quote }}
      protocol: TCP
      targetPort: {{ $container_port }}
      port: {{ $service_port }}
      {{- if and (eq "NodePort" $service_type) $node_port -}}
      nodePort: {{ $node_port }}
      {{- end }}
  selector: {{- include "zimagi-lib.selectorLabels" (list $root $service $name) | nindent 4 }}
{{- end -}}
{{- end -}}
