{{- /*
zimagi-lib.util.merge will merge two YAML templates and output the result.
This takes an array of three values:
- the root context
- the template name of the overrides (destination)
- the template name of the base (source)
*/}}
{{- define "zimagi-lib.util.merge" -}}
{{- $root := first . -}}
{{- $overrides := fromYaml (include (index . 1) $root) | default (dict ) -}}
{{- $tpl := fromYaml (include (index . 2) $root) | default (dict ) -}}
{{- toYaml (merge $overrides $tpl) -}}
{{- end -}}

{{- /*
zimagi-lib.util.ensureList will ensure the input is rendered as a list.
This takes a single value:
- the data item
*/}}
{{- define "zimagi-lib.util.ensureList" -}}
{{- if and . (kindIs "slice" .) -}}
{{- toYaml . -}}
{{- else -}}
{{- toYaml (ternary (list ) (list .) (empty .)) -}}
{{- end -}}
{{- end -}}
