{{- if  .Values.scheduler.psp.create -}}
apiVersion: {{ include "common.capabilities.policy.apiVersion" . }}
kind: PodSecurityPolicy
metadata:
  name: {{ template "zimagi.scheduler.fullname" . }}
  labels:
  {{- include "common.labels.standard" . | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  privileged: {{ .Values.scheduler.containerSecurityContext.privileged }}
  allowPrivilegeEscalation: false
  requiredDropCapabilities:
    - 'CAP_FOWNER'
  hostNetwork: false
  hostIPC: false
  hostPID: false
  runAsUser:
    rule: 'RunAsAny'
  seLinux:
    rule: 'RunAsAny'
  supplementalGroups:
    rule: 'RunAsAny'
  fsGroup:
    rule: 'RunAsAny'
  readOnlyRootFilesystem: false
{{- end }}